### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#10]

**Comment by ObeyVictoria** [comment]
[https://docs.google.com/document/d/1zSgL8ud9aG3ATaRIdljDrH6IYO158I3X6hG1wricUZQ/edit?usp=sharing](url)

Database Schema

**Comment by DaveWrites** [comment]
How's it coming for you @ObeyVictoria? Well done!!!

**Comment by Cozyamy** [comment]
Well done Victoria
