### ISSUE TITLE
Research plan

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#17]

**Comment by ValerieOsuamkpe** [comment]
Assignment done.
I worked on the Research background, Problem Statement, Research objectives and Research questions.
https://docs.google.com/document/d/1IL0Q5_j2FnKZR8Ny3pv-8h0nyWSlxzof9FuBrDZUWnQ/edit

**Comment by Gift-Victor** [comment]
I worked on some parts of the document, proofread, edited and compiled for project documentation.

**Comment by DaveWrites** [comment]
Well done teammates! We have documented the Research plan to detailed information about the problem statement our solution aims to solve and the research background. I was able to participate  in the brainstorming of added feature and also proofreading the document and approval.

**Comment by Cozyamy** [comment]
Good job!
