### ISSUE TITLE
User research

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#18]

**Comment by Gift-Victor** [comment]
The [user research](https://www.figma.com/file/res4sdWmcEBbOehYEF56al/User-research%2Fflow?node-id=0%3A1) has been completed. I worked on the Features list and User flow.

**Comment by Jero19** [comment]
The [user research](https://www.figma.com/file/res4sdWmcEBbOehYEF56al/User-research%2Fflow?node-id=0%3A1) has been completed. I was involved in the organization of interview notes, formation of some sections of the empathy map, brainstorming and prioritization of ideas.

**Comment by ValerieOsuamkpe** [comment]
The [user research](https://www.figma.com/file/res4sdWmcEBbOehYEF56al/User-research%2Fflow?node-id=0%3A1) has been completed. I actively participated in organizing participants notes, empathy mapping, extracting pain points, brainstorming and idea prioritization.

**Comment by Aruoturebishop** [comment]
The user research has been completed. I contributed in extracting of pain points of users, brainstorming possible solutions and prioritizing of ideas.

**Comment by DaveWrites** [comment]
I completed the User Research. They tasked me with the responsibility of the User personas, User story and brainstorming notes. 
I'm superelated with the collective effort by the team!

**Comment by Cozyamy** [comment]
Nice work team
