### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#19]

**Comment by Chibundum** [comment]
I worked on dropdowns, which were later redesigned by @lorengomez to suit our product.

https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=0%3A1

**Comment by lorengomez** [comment]
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=0%3A1

**Comment by DaveWrites** [comment]
Nice one @Chibundum

**Comment by ValerieOsuamkpe** [comment]
Well done, kindly keep our timeline in mind.

**Comment by lorengomez** [comment]
The basic style guide is done however, as we continue to design our high fidelity frames, the style guide will be iterated upon.

**Comment by Gift-Victor** [comment]
Well done guys!

**Comment by Gift-Victor** [comment]
The [style guide](https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=0%3A1) has been completed! 🥳
