### ISSUE TITLE
Research plan - Research background 

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#2]

**Comment by ValerieOsuamkpe** [comment]
Task done.
The research background gives an insight about our findings of the product industry, niche and existing problems.
Kindly find the research background in the [Research plan.](https://docs.google.com/document/d/1IL0Q5_j2FnKZR8Ny3pv-8h0nyWSlxzof9FuBrDZUWnQ/edit)

**Comment by DaveWrites** [comment]
Task completed!
Well done Mate!

**Comment by Cozyamy** [comment]
Great!

**Comment by Gift-Victor** [comment]
Nice job!
