### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#20]

**Comment by Chibundum** [comment]
I worked on Demo Page and Feature Page Lo-Fi Designs.

https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=514%3A304

https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1647%3A10567

**Comment by lorengomez** [comment]
I worked on the landing page, sign-up, and sign-in pages. These are the links to those frames accordingly.

https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=430%3A225

https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=773%3A3097

https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=814%3A3645

https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=812%3A2002

https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=814%3A5275

https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=980%3A4278

https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=980%3A5374

https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1003%3A3012

https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1008%3A5191

**Comment by DaveWrites** [comment]
Welldone @lorengomez, You have been instrument to the team.

**Comment by janefran** [comment]
Weldone Loren. I worked on error page and compare page.

**Comment by janefran** [comment]
I am about to start working on hifi design on about page.

**Comment by DaveWrites** [comment]
I like the team spirit. Welldone @janefran

**Comment by ValerieOsuamkpe** [comment]
Good job team.

**Comment by Chibundum** [comment]
I worked on pages for file upload: Wireframe, Lo-fi and Hi-Fi. These are the frames respectively.

WIREFRAMES
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1023%3A1990
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1023%3A2166
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1023%3A2526
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1023%3A2550

LO-FIs
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1321%3A8544
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1321%3A8640
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1321%3A8677
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1321%3A8582
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1321%3A8770
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1321%3A8729
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1354%3A11308

HI-FIs
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2351%3A17564
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2351%3A17725
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2351%3A17779
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2351%3A17650
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2351%3A17910
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2351%3A17848
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2351%3A18023

**Comment by Chibundum** [comment]
I worked on Dashboard wireframe

https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=833%3A2007

**Comment by Chibundum** [comment]
About to start working on Dashboard LO-FI

**Comment by purestc** [comment]
I worked on compare side by side screen wireframe
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=68%3A135
Spreadsheet lofi
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1482%3A4560
demo page hifi
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=774%3A1758
i'm about to start working on the dashboard page

**Comment by janefran** [comment]
I am done with the lo-fi and h-fi of the about pages. here are the links; 
Lo-fi; https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1851%3A11140 
Hi-fi; https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1969%3A13585 

the links to the error pages and the compare page I did
wireframing of error page; https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1066%3A2157
Lo-fi of error page; https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1066%3A2440
Lo-fi of compare page; https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=343%3A327

**Comment by Chibundum** [comment]
I worked on:

**Dashboard LO-FI Design**
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1618%3A10688

 **Dashboard Hi-Fi Design**
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2199%3A17487

(Task completed)

**Comment by lorengomez** [comment]
worked on the hi-fi design of the features page in tune with the low fi designed by @Chibundum. 


https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2160%3A17059

**Comment by purestc** [comment]
link to success page
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2851%3A64433
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2851%3A64443

link to spreadsheet used for the project designed by me
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2033%3A16055

wireframe of compare side by side
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1220%3A2645
