### ISSUE TITLE
Design documentation

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#21]

**Comment by Gift-Victor** [comment]
We've started this documentation though we can't share it since it hasn't been completed.

**Comment by ValerieOsuamkpe** [comment]
In progress

**Comment by DaveWrites** [comment]
In progress, will be upload here as we're done.

**Comment by Gift-Victor** [comment]
😅 So it's not as detailed as we'd like but it definitely explains our design process and contains relevant design documents. We might add more to it if there's a need to. Here's the [design documentation](https://docs.google.com/document/d/1JyFCwnTNvq4w8unjJTeqhAB9gXs-PpF-1cLrWa09D7M/edit?usp=sharing).
