### ISSUE TITLE
Team documentation

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#22]

**Comment by Gift-Victor** [comment]
The [project documentation](https://docs.google.com/document/d/1HjF1Dk0OlxHLxSltrga9uxH12cKEfUqXdyKtW1WWQAs/edit?usp=sharing) has been done. It was part of the documents we were to submit for the first presentation.

**Comment by ValerieOsuamkpe** [comment]
The project documentation includes an overview of the project and at the bottom of this file are all other available links associated with this project.

**Comment by DaveWrites** [comment]
We're still updating the PROJECT DOCUMENTATION as we make progress in this project phase. Everything about the project you can find in this doc.

Well done mates!

**Comment by Cozyamy** [comment]
Well done team
