### ISSUE TITLE
Project logo design

### ISSUE THREAD

**Issue by olasunkanmiUX** [zuri-training/EXCEL_COMP-Team_101#27]

**Comment by olasunkanmiUX** [comment]
We needed and identity design for the project. Dave and myself came up with several design options and our team voted for one of my logo design.

**Comment by DaveWrites** [comment]
![Testing dark mode Logo](https://user-images.githubusercontent.com/66538024/182435238-80e96b9f-9de8-4a80-85b0-c4f55ee25287.png)

You undoubtedly wonder what SimpliXL signifies and what the image would seem like when you hear the word. Its straightforward logo is displayed above.

You might also consider our decision to choose the color blue. Two components of the SimpliXL brand identity are as follows:

The blue logo for the SimpliXL brand design features white and blue script typography. When a user uses our service, the color blue stands for trust, loyalty, and honesty, giving them the impression that their data files are secure and not susceptible to attacks.


It is true that no other solution has a design just like simpliXL. SimpliXL prints its logo on specially formed and Overlay files demonstrating the ease of comparing excel contents. This demonstrates to clients how distinctive our offering will be. This is how credibility and trust are built through the logo design, and it works.

**Comment by Cozyamy** [comment]
Looks cool
