### ISSUE TITLE
Problem statement

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#3]

**Comment by ValerieOsuamkpe** [comment]
Task done. 
The problem statement encompasses the main problem SimpliXL seeks to solve.
Our problem statement can be found in our [Research plan.](https://docs.google.com/document/d/1IL0Q5_j2FnKZR8Ny3pv-8h0nyWSlxzof9FuBrDZUWnQ/edit)

**Comment by DaveWrites** [comment]
What's a solution without a problem? These questions are very critical and form the basis in which we'll came together to collaborate (Designers & Developers).
@ValerieOsuamkpe is an amazing mate and excited working with her.

**Comment by Cozyamy** [comment]
Well done team
