### ISSUE TITLE
Dashboard 

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#35]

**Comment by Chibundum** [comment]
I worked on:

**DASHBOARD WIREFRAME**
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=833%3A2007

**Comment by Chibundum** [comment]
I worked on:

**Dashboard LO-FI Design**
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1618%3A10688

**Comment by Chibundum** [comment]
Currently working on

**Dashboard HI-FI Design**
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2199%3A17487

**Comment by Jero19** [comment]
I worked on the LO-FI design of the **Dashboard**
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1618%3A10688

**Comment by Jero19** [comment]
**TASK Completed**
I worked on the HI-FI design of the Dashboard. The dashboard provides the user with access to the most important data.
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2199%3A17487

**Comment by Cozyamy** [comment]
ok, great
looks good

**Comment by Chibundum** [comment]
Task Completed

 **Dashboard Hi-Fi**
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2199%3A17487

**Comment by Chibundum** [comment]
The dashboard was iterated upon and the result was to create a version suitable for a new user with options to explore the features and tools of our web app. _Our initial dashboard design was for an existing user._

I worked on two new frames for the dashboard:

DASHBOARD HI-FI - NEW USER - OPTIONS
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2501%3A20965

DASHBOARD HI-FI - TOOLS
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2501%3A20469
