### ISSUE TITLE
Spreadsheet 

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#36]

**Comment by olasunkanmiUX** [comment]
@olasunkanmiUX  and @Aruoturebishop worked on the sheet outlook which was then replicated to show stages of document comparison
![image](https://user-images.githubusercontent.com/105271519/183501949-40ff7c4d-6a50-4072-9cb6-cee13f0d619c.png)

**Comment by Aruoturebishop** [comment]
I worked with @olasunkanmiUX in the design of the spreadsheet

**Comment by purestc** [comment]
I created the spreadsheet used for the project
![image](https://user-images.githubusercontent.com/81017637/183517199-9a7e253c-8ade-472a-bc0e-b392510b9251.png)

**Comment by DaveWrites** [comment]
From Bottom to Top shows the process of creating our unique and simple responsive spreadsheet.
