### ISSUE TITLE
Spreadsheet contents 

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#37]

**Comment by lorengomez** [comment]
Worked on the content of our spreadsheet file with @DaveWrites and @ValerieOsuamkpe

**Comment by ValerieOsuamkpe** [comment]
Task done.
I worked on the spreadsheet content for the comparison of two files

![image](https://user-images.githubusercontent.com/105221376/183489445-8255c40b-c51f-40b2-aefd-aa30fe8ca408.png)

**Comment by DaveWrites** [comment]
Task completed 
See [here](https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2851%3A65747)
