### ISSUE TITLE
Dashboard profile page

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#42]

**Comment by Yuuwaah** [comment]
Working on the nav bar and menu bar, finishing touches will be added in a bit

**Comment by Aruoturebishop** [comment]
I designed the layout of the Dashboard Profile page

**Comment by precious-me20102** [comment]
The dashboard gives an overview of a user project. it also gives our users a shortcut to the features. we made use of element like table, charts and gauges to show the overview.

**Comment by olasunkanmiUX** [comment]
I checked for consistency on the use of our brand colours on the dashboard as well as use of space.

**Comment by DaveWrites** [comment]
Find the Link to the completed design [here](https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2738%3A38254)

Well done guys
