### ISSUE TITLE
Terms of Service 

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#43]

**Comment by DaveWrites** [comment]
The Terms of service of simpliXL was drafted by and been completed into our designs.

**Comment by DaveWrites** [comment]
The Terms of Service can be seen [here](https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2851%3A64381)

**Comment by Cozyamy** [comment]
Well done
