### ISSUE TITLE
Compare files side by side page

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#44]

**Comment by ValerieOsuamkpe** [comment]
Task done.
The compare files side by side page shows two (2) excel sheets being displayed side by side on one (1) screen.

This page is prototyped to allow sheet 1 scroll horizonatlly in its position, and allow sheet 2 scroll horizonrally to overlap sheet 1, displaying its full content.
This particular protoype feature can be tested [here.](https://www.figma.com/proto/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2765%3A33196&scaling=scale-down&page-id=2%3A3&starting-point-node-id=2738%3A37047&show-proto-sidebar=1)

![image](https://user-images.githubusercontent.com/105221376/183477680-e5498ec5-c3c3-4aa0-9af3-83c66ee059c6.png)

**Comment by DaveWrites** [comment]
It feels so good to see the design work and to know that we design this from scratch. 
Thank you @purestc  and @ValerieOsuamkpe  for your effort on this task!

**Comment by DaveWrites** [comment]
![Highlighted Spreadsheet](https://user-images.githubusercontent.com/66538024/183489968-55bfa0aa-51e1-4bf4-b6c5-6beca522381e.png)

Above is the screen shot of a single file compare with highlighted duplicates and also other functions we want to achieve later with this project.
