### ISSUE TITLE
File upload page

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#46]

**Comment by Chibundum** [comment]
I worked on pages for file upload: Wireframe, Lo-fi and Hi-Fi. These are the frames respectively.

WIREFRAMES
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1023%3A1990
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1023%3A2166
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1023%3A2526
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1023%3A2550

LO-FIs
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1321%3A8544
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1321%3A8640
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1321%3A8677
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1321%3A8582
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1321%3A8770
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1321%3A8729
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=1354%3A11308

HI-FIs
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2351%3A17564
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2351%3A17725
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2351%3A17779
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2351%3A17650
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2351%3A17910
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2351%3A17848
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2351%3A18023

**Comment by Cozyamy** [comment]
Wow, that's great
