### ISSUE TITLE
Research questions

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#5]

**Comment by Jero19** [comment]
Done
I worked on the research questions. These are questions I hoped to get answers to at the end of the user interview https://1drv.ms/u/s!Ag42GNLr2kbwb0Ev9oEgejg4rLQ

**Comment by ValerieOsuamkpe** [comment]
Task done.
@Jero19 and I worked on the research questions for SimpliXL. 
The research questions are the main questions that guide us through uncovering users' behaviors and painpoints.
The research questions can be viewed in the [Research Plan.](https://docs.google.com/document/d/1IL0Q5_j2FnKZR8Ny3pv-8h0nyWSlxzof9FuBrDZUWnQ/edit)

**Comment by Jero19** [comment]
Task done.
@ValerieOsuamkpe and I worked on the research questions. The research questions are questions, which the research seeks to provide responses to in the course of conducting user interviews.
 [Research Plan.](https://docs.google.com/document/d/1IL0Q5_j2FnKZR8Ny3pv-8h0nyWSlxzof9FuBrDZUWnQ/edit)

**Comment by Cozyamy** [comment]
Well done team
