### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#55]

**Comment by olasunkanmiUX** [comment]
I am currently reviewing what has been done to agree on possible modifications or adjustment.

**Comment by Chibundum** [comment]
The dashboard was iterated upon and the result was to create a version suitable for a new user with options to explore the features and tools of our web app. Our initial dashboard design was for an existing user.

I worked on two new frames for the dashboard:

DASHBOARD HI-FI - NEW USER - OPTIONS
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2501%3A20965

DASHBOARD HI-FI - TOOLS
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2501%3A20469

**Comment by Jero19** [comment]
I and @Chibundum worked on the HI-FI of the dashboard for an already existing user. Designs can be seen[here](https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2844%3A54031)

**Comment by Gift-Victor** [comment]
Well done guys!

**Comment by Gift-Victor** [comment]
![image](https://user-images.githubusercontent.com/78073862/183500076-4c4f50df-0305-4aca-9dd4-8ee859e1f920.png)
 The dashboard was designed for both existing and new users. New users have the options of taking a tour of the app or using the compare feature.

**Comment by Dhavisco** [comment]
Well done guys... Nice designs.
Keep up the good work.
