### ISSUE TITLE
Prototyping

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#57]

**Comment by Gift-Victor** [comment]
So prototyping of the frames have been done but there are some little hiccups that have to be fixed.

**Comment by DaveWrites** [comment]
Well done for the team effort

**Comment by ValerieOsuamkpe** [comment]
Task done.
The figma prototype can be tested [here.](https://www.figma.com/proto/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2851%3A63809&scaling=scale-down&page-id=2%3A3&starting-point-node-id=2851%3A63809&show-proto-sidebar=1)

![image](https://user-images.githubusercontent.com/105221376/183475614-c073a046-552f-4836-a852-4287e3b0bd42.png)

**Comment by Jero19** [comment]
I worked with @DaveWrites @Gift-Victor @ValerieOsuamkpe to achieve the prototyping of both the website and web app. The prototype enabled us to test, evaluate and validate our ideas.

**Comment by DaveWrites** [comment]
So exciting to see the solution automated by prototyping.
