### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#58]

**Comment by Gift-Victor** [comment]
I'm still working on it 😅...

**Comment by DaveWrites** [comment]
On your mandate we believe... make it happen Boss

**Comment by Gift-Victor** [comment]
😂 using style-style to pressure me

**Comment by Gift-Victor** [comment]
I've made some screens responsive, though I encountered some difficulty. Here are the [screens](https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=3123%3A55724) and still working to do others.

**Comment by DaveWrites** [comment]
Thank you Gift for the effort and it feels so great to be in the same team with you.

**Comment by Gift-Victor** [comment]
🥺 And you too. Do well to share palliative sha 👀😏
