### ISSUE TITLE
Web app Onboarding Screens

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#59]

**Comment by Gift-Victor** [comment]
The Onboarding screens have been done

**Comment by DaveWrites** [comment]
Well Done @Gift-Victor

**Comment by Jero19** [comment]
Task done. I worked on the HIFI of the onboarding screens.
The links to the design [First onboarding screen](https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2550%3A23690) 
[Second onboarding screen](https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2550%3A23723)
