### ISSUE TITLE
Method & Recruiting

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#6]

**Comment by DaveWrites** [comment]
This task has been completed and entails our target audience and methodology approach to screening our potential users for interview. 
Thank you @precious-me20102 for making easy for me!

**Comment by precious-me20102** [comment]
Dave and I were able to work on the strategy in which we recruit our potential users for interviews and also streamlined the target users to 3.

**Comment by Cozyamy** [comment]
Good job!
