### ISSUE TITLE
Design process

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#69]

**Comment by Gift-Victor** [comment]
The team went through the process of understanding the brief, researching and analysing, before designing and implementing. These processes will be thoroughly explained in the design documentation when it's been completed.

**Comment by precious-me20102** [comment]
As a team we ensured we understood the brief. we research and also brainstorm before coming up with our designs and implementing them.

**Comment by DaveWrites** [comment]
As the name implies; Design process is a way of figuring out what you need to do, then doing it. Knowing the complexity of the problem, we were asked to solve. The team had to follow the design thinking framework, and that helps us in simplifying the whole process. We're very excited about the solution and creativity we're bringing to development.


The documents can be view [here](https://giftvictor.notion.site/Proj_team_101-Documents-2c743b920d604ca4af0cac8ded805329)

**Comment by ValerieOsuamkpe** [comment]
As a team, [we collectively understood the brief,](https://docs.google.com/document/d/1bhdKuai2Mw0Pq7voYjP4PNJ6c3FlfOctct_Z2JhJklY/edit?usp=sharing) put together our [research plan](https://docs.google.com/document/d/1IL0Q5_j2FnKZR8Ny3pv-8h0nyWSlxzof9FuBrDZUWnQ/edit?usp=sharing), dived into [documentation,](https://docs.google.com/document/d/1HjF1Dk0OlxHLxSltrga9uxH12cKEfUqXdyKtW1WWQAs/edit?usp=sharing) [user research and flow](https://www.figma.com/file/res4sdWmcEBbOehYEF56al/User-research%2Fflow?node-id=0%3A1) with interviews, creating our style guide and other components. 
We proceeded to [wireframing,](https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2%3A2) the developers began implementation the moment our first set of screens were ready, we did our [first presentation](https://www.loom.com/share/9b07644b44ff464a85743ae162034c31) using [slides](https://www.figma.com/file/WB1di7LNZu5KFPfYHSAT9e/Team-101-Excel-Comp-Presentation?node-id=0%3A1) to walk through and talk about problems, our key features and our solution as SimpliXL.
At the moment, the design is complete with its [prototyping](https://www.figma.com/proto/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2851%3A63809&scaling=min-zoom&page-id=2%3A3&starting-point-node-id=2851%3A63809&show-proto-sidebar=1).
All tasks can also be found here in our [GitHub repo](https://github.com/orgs/zuri-training/projects/290).
