### ISSUE TITLE
Screener questions

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#7]

**Comment by ValerieOsuamkpe** [comment]
Task done.

The screener questions helps filter/guide us to the right target audience for the project.
Kindly find the screener questions in the [Research plan.](https://docs.google.com/document/d/1IL0Q5_j2FnKZR8Ny3pv-8h0nyWSlxzof9FuBrDZUWnQ/edit)

**Comment by precious-me20102** [comment]
The screener questions help decide who takes the survey based on our target audience for the project. The Research plan contain the screener questions

**Comment by Cozyamy** [comment]
Well done team
