### ISSUE TITLE
Feature Explore Page

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#70]

**Comment by Gift-Victor** [comment]
The explore page gives users the option of taking a tour of the app or using the comparator. The idea behind it, is to show users the features of the app and how it works. 
![image](https://user-images.githubusercontent.com/78073862/183504695-d6e5608a-6167-46e4-897a-6cd6b4282f8c.png)

**Comment by DaveWrites** [comment]
Amazing design lead.. Well done @Gift-Victor

**Comment by Dhavisco** [comment]
That's great.
