### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#8]

**Comment by Yuuwaah** [comment]
We are still within the timeline of the project.

**Comment by janefran** [comment]
Still in progress.

**Comment by olasunkanmiUX** [comment]
In progress

**Comment by DaveWrites** [comment]
@Gift-Victor  @ValerieOsuamkpe  Kindly evaluate the entire project phase and give feedback if we were able to meet all the set timelines in this project Phase. 

Thank you guy for checkmating us with the time to deliver.

**Comment by DaveWrites** [comment]
As lead of each subgroup. Kindly comment on our progress thus far!

**Comment by Gift-Victor** [comment]
For the design aspect, we are on track, the design documentation should have been completed before the deadline.

**Comment by ValerieOsuamkpe** [comment]
Milestone 1: Research and breakdown of data, was well completed within the timeline set for it.

Each completed task gets a strikethrough on our [notion board.](https://giftvictor.notion.site/Proj_team_101-6888931b86284f6c92d2d25acb6e4e37)

![image](https://user-images.githubusercontent.com/105221376/183508951-e25053fc-c11b-452c-bdce-ae428427f047.png)

**Comment by precious-me20102** [comment]
Milestone 3: Hi-Fi Designs and prototyping 

The Task was completed within the timeline and we are able to submit the Hi-fi designs before the deadline closes by the Zuri coordinators

The team assigned to Hi-fi design task was cooperative enough to see off this time
![Capture high fi](https://user-images.githubusercontent.com/105180283/183521972-80aa7352-46e8-4b2b-9330-98dad48057ea.PNG)
![Capture timeline](https://user-images.githubusercontent.com/105180283/183522408-c29fa315-0d13-4781-9ded-ca2af1e6f02c.PNG)

**Comment by Gift-Victor** [comment]
We didn't meet the deadline we set for ourselves 😅 but we are on track with the project in general.
