### ISSUE TITLE
Header page/Menu bar

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#86]

**Comment by lorengomez** [comment]
Designed the header components used in our website design.

https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=455%3A294

**Comment by Yuuwaah** [comment]
Worked on the nav bar and menu bar for the dashboard profile page 
https://www.figma.com/file/UV7dpsrV768tBbfFN8eWsz/simpliXL?node-id=2006%3A13358
