### ISSUE TITLE
Interview scripts

### ISSUE THREAD

**Issue by Cozyamy** [zuri-training/EXCEL_COMP-Team_101#9]

**Comment by precious-me20102** [comment]
The interview scripts consist of some set of questions we asked our users in order to find out their pain point and also gain an insight on their experience concerning the product.

**Comment by DaveWrites** [comment]
Well done mate!

**Comment by precious-me20102** [comment]
![IMG-20220804-WA0006](https://user-images.githubusercontent.com/105180283/182839015-09d0d17f-90f7-4847-afc8-1d8c2c008802.jpg)
![IMG-20220804-WA0007](https://user-images.githubusercontent.com/105180283/182839252-f091dff6-9128-4245-bfd0-81d42c258d54.jpg)

![IMG-20220804-WA0008](https://user-images.githubusercontent.com/105180283/182839274-d275c135-7bae-4944-9c52-2ca5f680c853.jpg)
![IMG-20220804-WA0009](https://user-images.githubusercontent.com/105180283/182839310-e1b992ad-6bbe-48c4-9c9e-382e90a206cc.jpg)

**Comment by Cozyamy** [comment]
Good job
